### ISSUE TITLE
Tab & TabItems depends on filter/poodll

### ISSUE THREAD

**Issue by nadavkav** [justinhunt/moodle-atto_generico#2]
Trying to use Tabs & TabItem presets, I was gently "asked" by the Chrome js console to install filter/poodll :wink: 

See error:
"http://our-moodle-site/filter/poodll/3rdparty/jqueryui/jquery-ui.min.css Failed to load resource: the server responded with a status of 404 (Not Found)"

Workaround: Install filter/poodll
Workaround 2: copy filter/poodll/3rdparty/jqueryui/jquery-ui.min.css info filter/generico and update preset.

**Comment by justinhunt** [comment]
This should be fixed in the latest commit 
https://github.com/justinhunt/moodle-atto_generico/commit/75cb713ab86e786ce9632fa9a4dcc99f08283f0f 
and will be in Moodle.org in a few minutes)
I used a CDN to fetch the libs. For templates that makes them shareable.

**Comment by nadavkav** [comment]
Sweet :smile:
