### ISSUE TITLE
Link from Moodle Plugin site to documentation is broken

### ISSUE THREAD

**Issue by whanrott** [justinhunt/moodle-atto_generico#3]
The link to "More documentation on this plugin" on [https://moodle.org/plugins/atto_generico](https://moodle.org/plugins/atto_generico) gives a 404 error

The link points to the HTTP version of demo.poodll.com. Visiting the same URL with HTTPS works.

**Comment by justinhunt** [comment]
Thanks for the heads up! I changed it to:
https://docs.moodle.org/en/filter_generico

Thanks
